# Generated by Django 6.0 on 2025-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='blog'),
        ),
    ]
