# Generated by Django 6.0 on 2025-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_post_publish_date_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='bloging', max_length=255),
        ),
    ]
