# Generated by Django 6.0 on 2025-12-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_categort_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categort',
            new_name='Category',
        ),
    ]
