# Generated by Django 6.0 on 2025-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='websit_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
