# Generated by Django 6.0 on 2025-12-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
